esphome:
  name: basic-r1-52
  friendly_name: Basic R1_52

esp8266:
  board: sonoff_basic

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rHg1gLKS0+ZYdn4vqyyVYDzWadIINw16qRI1KFrv3yE="

ota:
  - platform: esphome
    password: "e8758301ecb2a24588b3a554aaf8c4ce"

wifi:
  ssid: "Bradley-IOT"
  password: "Wifi_pwd"
  manual_ip:
    static_ip: 192.168.21.52
    gateway: "GW"
    subnet: "SN"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff-Basic-R1 Fallback Hotspot"
    password: "JpaRo7hzInzA"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button
    on_press:
      then:
        - switch.toggle: relay

  - platform: status
    name: "R51 Status"

switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    name: "relay"


status_led:
  pin:
    number: GPIO13
    inverted: yes

sensor:
# Reports the WiFi signal strength
  - platform: wifi_signal
    name: r51 Signal
    update_interval: 60s
